#!/bin/sh

COMMIT=`head -n1 $1`

if [[ ! "$COMMIT" =~ ^UPDATE:  ]]; then
    echo -e "Expresion en el mensaje del commit incorrecta \nFormato correcto: UPDATE: mensaje_del_commit" 1>&2
    exit 1
fi


